version: '3.7'
services:

  iris:
    build:
      context: .
    image: iris_oauth2
    hostname: iris
    command: -b "sudo service apache2 start"
    volumes: 
    - "./:/tmp"
    ports:
    - "81:52773"
    - "80:80"
    - "443:443"
